//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public int Id { get; set; }
        public string Certificate { get; set; }
        public string Otorgante { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> DateCert { get; set; }
        public bool Actually { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
