//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public string Site { get; set; }
        public string Sector { get; set; }
        public string RazonSocial { get; set; }
        public string Telefono { get; set; }
        public string Nit { get; set; }
        public int NumeroEmp { get; set; }
        public string Description { get; set; }
        public string IdUser { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Company Company2 { get; set; }
    }
}
