//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferPhas
    {
        public int Id { get; set; }
        public int IdOffer { get; set; }
        public string Name { get; set; }
        public System.DateTime InitPhase { get; set; }
        public System.DateTime FinishPhase { get; set; }
        public decimal Value { get; set; }
        public Nullable<short> StatusPhase { get; set; }
    
        public virtual Offer Offer { get; set; }
    }
}
