//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.OfferPhases = new HashSet<OfferPhas>();
            this.OfferUsers = new HashSet<OfferUser>();
            this.Projects = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> PrecioFijo { get; set; }
        public bool Sale { get; set; }
        public int ValueFixedProject { get; set; }
        public short NumberPhases { get; set; }
        public bool AutomaticValuePhases { get; set; }
        public string IdUser { get; set; }
        public int CategoryId { get; set; }
        public string TitleOffer { get; set; }
        public string Description { get; set; }
        public Nullable<int> RangoValor { get; set; }
        public Nullable<System.DateTime> DateOffer { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferPhas> OfferPhases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferUser> OfferUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}
