//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public  class Company
    {



        public int Id { get; set; }
        [DefaultValue("")]
        public string Name { get; set; }
        [DefaultValue("")]
        public string Mail { get; set; }
        [DefaultValue("")]
        public string Site { get; set; }
        [DefaultValue("")]
        public string Sector { get; set; }
        [DefaultValue("")]
        public string RazonSocial { get; set; }
        [DefaultValue("")]
        public string Telefono { get; set; }
        [DefaultValue("")]
        public string Nit { get; set; }
        public int NumeroEmp { get; set; }
        [DefaultValue("")]
        public string Description { get; set; }
        [DefaultValue("")]
        public string IdUser { get; set; }

        public virtual RegisterBindingModel AspNetUsers { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Company Company2 { get; set; }
    }
}
