//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
       public List<Experience> Experiences { get; set; }
        public List<Education> Educations { get; set; }
        public List<Certification> Certifications { get; set; }
        public List<Language> Languages { get; set; }
        public RegisterBindingModel User { get; set; }
        

    }
}
