//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Experience
    {
        public int Id { get; set; }
        public string UserId { get; set; }

        public string Company { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public string  DateIni { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public string DateEnd { get; set; }
        public bool CurrentEmploy { get; set; }
        public string Position { get; set; }
        public string FunctionPosition { get; set; }
       

        public string Company2 { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public string DateIni2 { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public string DateEnd2 { get; set; }
        public bool CurrentEmploy2 { get; set; }
        public string Position2 { get; set; }
        public string FunctionPosition2 { get; set; }

        public string Company3 { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public string DateIni3 { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public string DateEnd3 { get; set; }
        public bool CurrentEmploy3 { get; set; }
        public string Position3 { get; set; }
        public string FunctionPosition3 { get; set; }


        public virtual RegisterBindingModel AspNetUser { get; set; }
    }
}
