//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LevelLang { get; set; }
        public bool Certificate { get; set; }
        public string UserId { get; set; }
    
        public virtual RegisterBindingModel AspNetUser { get; set; }
        public string Name2 { get; set; }
        public string LevelLang2 { get; set; }
        public bool Certificate2 { get; set; }
        public string Name3 { get; set; }
        public string LevelLang3 { get; set; }
        public bool Certificate3 { get; set; }
    }
}
