//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortFolio
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string UserId { get; set; }
        public int CategoriaId { get; set; }
        public string Categoria { get; set; }
        public string Description { get; set; }
        public string Imagen { get; set; }
        public bool TermCopy { get; set; }
        public List<Category> Categories { get; set; }
        //adiciones del 19 de julio 2016 correo cristhian
        public string Cliente { get; set; }
        //El campo nombre de autor sí hace referencia a la persona que creó esa entrada de portafolio, el cual debe ser un Freelance previamente registrado.
        public RegisterBindingModel Autor { get; set; }
        //
        public virtual RegisterBindingModel AspNetUser { get; set; }

    }
}
