//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Persistence.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using BB.SmsQuiz.Infrastructure.Domain;

    public  class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.AspNetUsers = new AspNetUsers();
        }


        public int Id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public string Site { get; set; }
        public string Sector { get; set; }
        public string RazonSocial { get; set; }
        public string Telefono { get; set; }
        public string Nit { get; set; }
        public int NumeroEmp { get; set; }
        public string Description { get; set; }
        public string IdUser { get; set; }

        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Company Company2 { get; set; }
    }
}
