//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

 namespace ZonaFl.Persistence.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public System.DateTime DateIni { get; set; }
        public System.DateTime DateEnd { get; set; }
        public bool CurrentEmploy { get; set; }
        public string Position { get; set; }
        public string FunctionPosition { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUsers AspNetUser { get; set; }
    }
}
