//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaFl.Persistence.Entities
{
    using System;
    using System.Collections.Generic;
    using BB.SmsQuiz.Infrastructure.Domain;
    using System.ComponentModel.DataAnnotations;

    public partial class PortFolio:  EntityBase, IAggregateRoot
    {
        
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string UserId { get; set; }
        public int CategoriaId { get; set; }
        public string Description { get; set; }
        public string Imagen { get; set; }
        public bool TermCopy { get; set; }
        public string Cliente { get; set; }

        public virtual AspNetUsers AspNetUser { get; set; }
    }
}
